name: Docker CI

on:
  pull_request:
  push:
    branches: [main]
  schedule:
    - cron: "0 15 * * 0"
  workflow_call:
  workflow_dispatch: # for debug

permissions: read-all

env:
  IMAGE_NAME: ${{ github.repository }}

jobs:
  dockerize:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab

      - name: Setup docker environment
        uses: ./.github/actions/docker-setup

      - name: Build container
        id: build
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          tags: ${{ env.IMAGE_NAME }}:alpha
          context: .
          outputs: type=docker,dest=/tmp/myimage.tar

      - name: Upload container image to artifact
        uses: actions/upload-artifact@0b7f8abb1508181956e8e162db84b466c27e18ce
        with:
          name: myimage
          path: /tmp/myimage.tar
          retention-days: 1

  scan-trivy:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
    needs: dockerize
    steps:
      - name: Checkout repository
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab

      - name: Setup docker environment
        uses: ./.github/actions/docker-setup

      - name: Download container image from artifact
        uses: actions/download-artifact@9782bd6a9848b53b110e712e20e42d89988822b7
        with:
          name: myimage
          path: /tmp

      - name: Load container image
        run: docker load --input /tmp/myimage.tar

      - name: Scan container image by trivy
        uses: aquasecurity/trivy-action@b43daad0c3c96202fc5800b511dfae8e6ecce864
        with:
          image-ref: "${{ env.IMAGE_NAME }}:alpha"
          format: "template"
          template: "@/contrib/sarif.tpl"
          output: "trivy-results.sarif"
          severity: "CRITICAL,HIGH"

      - name: Publish trivy report to GitHub Security
        uses: github/codeql-action/upload-sarif@cdcdbb579706841c47f7063dda365e292e5cad7a
        with:
          sarif_file: "trivy-results.sarif"

  scan-grype:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
    needs: dockerize
    steps:
      - name: Checkout repository
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab

      - name: Setup docker environment
        uses: ./.github/actions/docker-setup

      - name: Download container image from artifact
        uses: actions/download-artifact@9782bd6a9848b53b110e712e20e42d89988822b7
        with:
          name: myimage
          path: /tmp

      - name: Load container image
        run: docker load --input /tmp/myimage.tar

      - name: Scan container image by grype
        id: grype-image
        uses: anchore/scan-action@4be3c24559b430723e51858969965e163b196957
        with:
          image: "${{ env.IMAGE_NAME }}:alpha"
          severity-cutoff: low
          fail-build: false
          acs-report-enable: true

      - name: Publish grype report to GitHub Security
        uses: github/codeql-action/upload-sarif@cdcdbb579706841c47f7063dda365e292e5cad7a
        with:
          sarif_file: ${{ steps.grype-image.outputs.sarif }}

  sast-grype:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab

      - name: Scan Dockerfile by grype
        id: grype-files
        uses: anchore/scan-action@4be3c24559b430723e51858969965e163b196957
        with:
          path: "."
          severity-cutoff: low
          fail-build: false
          acs-report-enable: true

      - name: Publish grype report to GitHub Security
        uses: github/codeql-action/upload-sarif@cdcdbb579706841c47f7063dda365e292e5cad7a
        with:
          sarif_file: ${{ steps.grype-files.outputs.sarif }}

  sast-hadolint:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab

      - name: Scan Dockerfile by hadolint
        uses: hadolint/hadolint-action@54c9adbab1582c2ef04b2016b760714a4bfde3cf
        with:
          recursive: true
          format: sarif
          output-file: hadolint-results.sarif
          no-fail: true

      - name: Publish hadolint report to GitHub Security
        uses: github/codeql-action/upload-sarif@cdcdbb579706841c47f7063dda365e292e5cad7a
        with:
          sarif_file: hadolint-results.sarif
          wait-for-processing: true
